<footer class="footer-section"><div class="container">
		     <?php 
    $store_info=DB::table('store_info')->first();
    ?>
			<div class="row"><div class="col-xs-12 col-sm-12 col-md-6"><div class="row"><div class="col-xs-12 col-sm-4 col-md-4"><div class="widget"><h6 class="mb20">Quick Links</h6><div class="footer-links"><ul><li><a href="{{route('index')}}">Home</a> </li><li><a href="{{route('page_url',['about_us'])}}">About Us</a> </li>    <li><a href="{{ route('contact')}}">Contact Us</a> </li><li><a href="{{ route('mydashboard')}}">My Accounts</a> </li></ul></div></div></div><div class="col-xs-12 col-sm-4 col-md-5"><div class="widget"><h6 class="mb20">Customised Services</h6><div class="footer-links"><ul><li><a href="{{route('page_url',['privacy-policy'])}}">Privacy policy</a> </li><!--<li><a href="{{ route('exchange')}}">Exchange</a> </li>--><li><a href="{{route('page_url',['return_policy'])}}"  >Return policy</a> </li><li><a href="{{route('page_url',['payment'])}}">Payment policy </a> </li><!--<li><a href="{{route('page_url',['delivery_policy'])}}">Payment policy </a> </li>--><li><a href="{{route('page_url',['terms'])}}"> Terms & Conditions </a> </li></ul></div></div></div><div class="col-xs-12 col-sm-4 col-md-3"><div class="widget"><h6 class="mb20"> Company</h6><div class="footer-links"><ul><li><a href="{{route('faq',[base64_encode(1)])}}">FAQs</a> </li>  <li><a href="{{route('refer_and_earn')}}">Refer & Earn</a> </li> </ul></div></div></div></div></div><div class="clearfix visible-sm"></div><div class="col-xs-12 col-sm-12 col-md-6"><div class="row"><div class="col-xs-12 col-sm-6 col-md-6"><div class="widget"><h6 class="mb20">Connect with us</h6><div class="footer-social"><ul><li><a href="{{$store_info->facebook_url}}" target="_blank"><i class="fa fa-facebook"></i> </a> </li><li><a href="{{$store_info->twiter_url}}" target="_blank"><i class="fa fa-twitter"></i> </a> </li><li><a class="snap" href="{{$store_info->snapchat_url}}" target="_blank"><i class="fa fa-snapchat-ghost"></i></a></li><li><a href="{{$store_info->linkedin_url}}" target="_blank"><i class="fa fa-instagram"></i> </a> </li></ul></div><h6>pay using</h6><div class="onlineicon"><a href="#"><img src="{{ asset('public/fronted/images/paypal.png') }}" alt=""> </a><a href="#"><img src="{{ asset('public/fronted/images/maestro.png') }}" alt=""> </a><a href="#"><img src="{{ asset('public/fronted/images/discover.png') }}" alt=""> </a><a href="#"><img src="{{ asset('public/fronted/images/visa.png') }}" alt=""> </a></div></div></div><div class="col-xs-12 col-sm-6 col-md-6"><div class="widget"><h6 class="mb20">Subscribe to Newsletter</h6><p>Subscribe to our newsletter and get10% off your first purchase</p>
						<form  method="Post" action="{{route('subscribe')}}">
                                  @csrf
                            @if ($errors->any())
                            @foreach ($errors->all() as $error)
                            <span class="help-block"><p style="color:red">{{$error}}</p></span>
                            @endforeach
                            @endif<input type="text" name="email" placeholder="Your Email Address"><button type="submit" class="subscribe">Subscribe </button></form></div></div></div></div></div></div>
		<section class="copyright-section"><div class="container"><div class="row"><div class="col-sm-12 col-md-12 text-center"><div class="copyright"><p>© 2023, kefih | All Rights Reserved  </p></div></div><!--<div class="col-sm-5 col-md-3 text-rgt"><div class="copyright"><p>Powered by: <a href="https://www.b2cinfosolutions.com/" target="_blank">B2C Info Solutions</a></p></div></div>--></div></div></section></footer>
